# allow npm install from private github repository, see https://cloud.google.com/build/docs/access-github-from-build
steps:
  - name: 'gcr.io/cloud-builders/git'
    secretEnv: ['SSH_KEY']
    entrypoint: 'bash'
    args:
    - -c
    - |
      echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=" > /root/.ssh/known_hosts
      echo "$$SSH_KEY" >> /root/.ssh/id_rsa
      chmod 400 /root/.ssh/id_rsa
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  - name: node:20
    args:
      - install
    entrypoint: npm
    volumes:
    - name: 'ssh'
      path: /root/.ssh
  - name: node:20
    args:
      - run
      - build
    entrypoint: npm
  - name: bash
    args:
      - mkdir
      - docs/dist
  - name: bash
    args:
      - cp
      - '-r'
      - dist/weatherlayers-deck.umd.min.js
      - dist/weatherlayers-client.umd.min.js
      - dist/weatherlayers-standalone.umd.min.js
      - docs/dist
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-m'
      - rsync
      - '-r'
      - '-d'
      - ./docs
      - 'gs://$_STORAGE_BUCKET'
options:
  machineType: 'E2_HIGHCPU_8'
availableSecrets:
  secretManager:
  - versionName: projects/1013855669850/secrets/cloudbuild-deploy-key/versions/latest
    env: 'SSH_KEY'