steps:
  - name: node:20
    args:
      - install
    entrypoint: npm
  - name: node:20
    args:
      - run
      - build
    entrypoint: npm
  - name: bash
    args:
      - mkdir
      - docs/dist
  - name: bash
    args:
      - cp
      - '-r'
      - dist/weatherlayers-deck.umd.min.js
      - dist/weatherlayers-client.umd.min.js
      - docs/dist
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-m'
      - rsync
      - '-r'
      - '-d'
      - ./docs
      - 'gs://$_STORAGE_BUCKET'
options:
  machineType: 'E2_HIGHCPU_8'