steps:
  - name: node
    args:
      - install
      - '--legacy-peer-deps'
    entrypoint: npm
  - name: node
    args:
      - run
      - build
    env:
      - 'NODE_OPTIONS=--max-old-space-size=4096'
      - 'LICENSE_DOMAIN=weatherlayers.com'
    entrypoint: npm
  - name: bash
    args:
      - mkdir
      - docs/dist
  - name: bash
    args:
      - cp
      - '-r'
      - dist/weatherlayers-deck.umd.min.js
      - dist/weatherlayers-client.umd.min.js
      # - dist/weatherlayers-standalone.umd.min.js
      - docs/dist
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-m'
      - rsync
      - '-r'
      - '-d'
      - ./docs
      - 'gs://$_STORAGE_BUCKET'
